/*
 * (c)2013 Swisscom (Schweiz) AG.
 *
 * @(#) $Id: vp5resAnliegenMenuFixnet.drl 147 2013-11-13 12:35:18Z tolvoph1 $
 * $Author: tolvoph1 $
 * $Date: 2013-11-13 13:35:18 +0100 (Wed, 13 Nov 2013) $
 * $Revision: 147 $
 */
package com.nortel.ema.swisscom.bal.rules.menu.oneIVR

import com.nortel.ema.swisscom.bal.vo.model.CustomerProfile;
import com.nortel.ema.swisscom.bal.vo.model.CustomerProducts;
import com.nortel.ema.swisscom.bal.vo.model.CallProfile;
import com.nortel.ema.swisscom.bal.vo.model.CallDetail;
import com.nortel.ema.swisscom.bal.vo.model.ServiceConfigurationMap;
import com.nortel.ema.swisscom.bal.rules.model.facts.R5RulesBean;
import com.nortel.ema.swisscom.bal.menu.model.ExtendedMenuOption;
import java.util.List;

global List menuOptions;
global String language;

function ExtendedMenuOption kundendienstTransfer() {
  	  ExtendedMenuOption option = new ExtendedMenuOption();
  	  option.setName("KUNDENDIENST");
  	  option.setPrompt("alm-kundendienst");
  	  option.setEmergencyText("SF");
  	  option.setAction("TRANSFER");
  	  return option;
}

function ExtendedMenuOption kundendienstMenu() {
  	  ExtendedMenuOption option = new ExtendedMenuOption();
  	  option.setName("KUNDENDIENST");
  	  option.setPrompt("alm-kundendienst");
  	  option.setEmergencyText("SF");
  	  option.setAction("MENU");
  	  return option;
}

function ExtendedMenuOption rechnungTransfer() {
  	  ExtendedMenuOption option = new ExtendedMenuOption();
  	  option.setName("RECHNUNG");
  	  option.setPrompt("alm-rechnung");
  	  option.setEmergencyText("RECHNUNG");
  	  option.setAction("TRANSFER");
  	  return option;
}

function ExtendedMenuOption stoerungMenu() {
  	  ExtendedMenuOption option = new ExtendedMenuOption();
  	  option.setName("STOERUNG");
  	  option.setPrompt("alm-stoerung");
  	  option.setEmergencyText("SA");
  	  option.setAction("MENU");
  	  return option;
}
 
/*
	Initialize Rules Bean and check for String values in passed
	parameters. Put those in "constants" attributes of the bean
*/
rule "Init"
	no-loop
	salience 20000
	when
		not (R5RulesBean(  ))
	then
		assert ( new R5RulesBean(), true );
end

rule "AnliegenMenu_RES"
  no-loop
  when
    handle: R5RulesBean( state != R5RulesBean.ANLIEGENMENU_DONE )
  then
	  menuOptions.add(kundendienstTransfer());
	  menuOptions.add(stoerungMenu());
      menuOptions.add(rechnungTransfer());
	  handle.setState ( R5RulesBean.ANLIEGENMENU_DONE );  
end
 

 