/*
 * (c)2014 Swisscom (Schweiz) AG.
 *
 * @(#) $Id: vp5res-0800406080-menu-level2.drl 223 2014-03-20 13:34:09Z tolvoph1 $
 * $Author: tolvoph1 $
 * $Date: 2014-03-20 14:34:09 +0100 (Thu, 20 Mar 2014) $
 * $Revision: 223 $
 */
package com.nortel.ema.swisscom.bal.rules.menu.oneIVR

import com.nortel.ema.swisscom.bal.vo.model.CustomerProfile;
import com.nortel.ema.swisscom.bal.vo.model.CustomerProducts;
import com.nortel.ema.swisscom.bal.vo.model.CallProfile;
import com.nortel.ema.swisscom.bal.vo.model.CallDetail;
import com.nortel.ema.swisscom.bal.rules.model.facts.R5RulesBean;
import com.nortel.ema.swisscom.bal.menu.model.ExtendedMenuOption;
import java.util.List;

global List menuOptions;
global String language;

function ExtendedMenuOption res() {
  	  ExtendedMenuOption option = new ExtendedMenuOption();
  	  option.setName("RES");
  	  option.setPrompt("pm-privatkundenprodukte");
  	  option.setEmergencyText("RES");
  	  option.setAction("TRANSFER");
  	  return option;
}

function ExtendedMenuOption sme() {
  	  ExtendedMenuOption option = new ExtendedMenuOption();
  	  option.setName("SME");
  	  option.setPrompt("pm-geschaeftskundenprodukte");
  	  option.setEmergencyText("SME");
  	  option.setAction("MENU");
  	  return option;
}
 
// Statisches Menue, da es nur unter einer Menüoption angeboten wird
rule "TASMenuLevel2"
	no-loop
	when

	then
	  menuOptions.add(res()); 
	  menuOptions.add(sme());
end

 