/*
 * (c)2014 Swisscom (Schweiz) AG.
 *
 * @(#) $Id: vp5resAnliegenMenuOnlineShop.drl 231 2014-04-07 07:25:35Z tolvoph1 $
 * $Author: tolvoph1 $
 * $Date: 2014-04-07 09:25:35 +0200 (Mon, 07 Apr 2014) $
 * $Revision: 231 $
 * $URL: http://sol47658/svn/BAL_Rules/trunk/BAL_Rules/src/rules/menu/oneIVR/vp5resAnliegenMenuOnlineShop.drl $
 */
package com.nortel.ema.swisscom.bal.rules.menu.oneIVR

import com.nortel.ema.swisscom.bal.vo.model.CustomerProfile;
import com.nortel.ema.swisscom.bal.vo.model.CustomerProducts;
import com.nortel.ema.swisscom.bal.vo.model.CallProfile;
import com.nortel.ema.swisscom.bal.vo.model.CallDetail;
import com.nortel.ema.swisscom.bal.rules.model.facts.R5RulesBean;
import com.nortel.ema.swisscom.bal.menu.model.ExtendedMenuOption;
import java.util.List;

global List menuOptions;
global String language;

function ExtendedMenuOption tvInternetAdmin() {
  	  ExtendedMenuOption option = new ExtendedMenuOption();
  	  option.setName("TVA");
  	  option.setEmergencyText("TVA");
  	  option.setPrompt("alm-tv-internet-admin");
  	  option.setAction("TRANSFER");
  	  return option;
} 

function ExtendedMenuOption allesAndere() {
  	  ExtendedMenuOption option = new ExtendedMenuOption();
  	  option.setName("AA");
  	  option.setEmergencyText("AA");
  	  option.setPrompt("alm-alles-andere");
  	  option.setAction("TRANSFER");
  	  return option;
} 
 
rule "AnliegenMenuOnlinShop"
	no-loop
	when

	then
	  menuOptions.add(tvInternetAdmin()); 
	  menuOptions.add(allesAndere()); 
	  
end

 