package com.nortel.ema.swisscom.bal.state

/*
	@(#) $Id: vp5sme-0800851851-state.drl 170 2014-01-28 10:26:21Z tolvoph1 $
	$Author: tolvoph1 $
	
	Callflow for SME Shophotline 0800 851 851
		
*/

import com.nortel.ema.swisscom.bal.vo.model.CustomerProfile;
import com.nortel.ema.swisscom.bal.vo.model.CustomerProducts;
import com.nortel.ema.swisscom.bal.vo.model.CallProfile;
import com.nortel.ema.swisscom.bal.vo.model.CallDetail;
import com.nortel.ema.swisscom.bal.vo.model.ServiceConfigurationMap;
import com.nortel.ema.swisscom.bal.rules.model.StateEngineRulesResult;
import com.nortel.ema.swisscom.bal.rules.model.facts.R5RulesBean;
import org.apache.commons.lang.StringUtils;
import java.util.Set;
import java.util.Date;

/*
	Initialize Rules Bean and check for String values in passed
	parameters. Put those in "constants" attributes of the bean
*/
rule "001_Init_R5RulesBean"
	no-loop
	salience 20000
	when
		not (R5RulesBean(  ))
	then
		assert ( new R5RulesBean(), true );
end

/* ****************************************************************************************
   Start of the rules
   ****************************************************************************************/

/* 
 First state:
 - Init with ANI -> SetPNFromSession
 - Init without ANI -> play jingle
 - Seiteneinstieg -> Info
 */
rule "010a_Init_NoAni"
	no-loop
	salience -100
	when
		(
			CallProfile ( nextState == "Init", ani == "" ) || 
			CallProfile ( nextState == "Init", ani == "0" ) || 
			CallProfile ( nextState == "Init", ani == null )    
		)
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("PROCEED");		
		serr.setNextState("Welcome");
		serr.setState(StateEngineRulesResult.DONE);
end

rule "010b_Init_GotAniSetPNFromSession"
	no-loop
	salience -1000
	when
		CallProfile ( nextState == "Init" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("SETPNFROMSESSION");		
		serr.setOutputVar1("false");
		serr.setNextState("AutoLangSelect");
		serr.setState(StateEngineRulesResult.DONE);
end

/* Automatic language selection based on decision matrix or offer language selection */
rule "020a_AutoLangSelect_Wireline_multiLanguageRegion"
	no-loop
	when
		callProfile: CallProfile ( nextState == "AutoLangSelect", singleLanguage == "false", connectionType == R5RulesBean.WIRELINE )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("SETLANG");		
		serr.setOutputVar1("g");
		serr.setNextState("Welcome-MultiLanguage");
		serr.setState(StateEngineRulesResult.DONE);
end

rule "020b_AutoLangSelect_Wireline_singleLanguageRegion"
	no-loop
	when
		callProfile: CallProfile ( nextState == "AutoLangSelect", singleLanguage == "true", connectionType == R5RulesBean.WIRELINE )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("SETLANG");		
		serr.setOutputVar1(callProfile.getLanguage());
		serr.setNextState("Welcome-SingleLanguage");
		serr.setState(StateEngineRulesResult.DONE);
end

rule "020c_AutoLangSelect_unknown_singleLanguageRegion"
	no-loop
	when
		callProfile: CallProfile ( nextState == "AutoLangSelect", singleLanguage == "true", connectionType == R5RulesBean.UNKNOWN )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("SETLANG");		
		serr.setOutputVar1(callProfile.getLanguage());
		serr.setNextState("Welcome-SingleLanguage");
		serr.setState(StateEngineRulesResult.DONE);
end

rule "020d_AutoLangSelect_unknown_multiLanguageRegion"
	no-loop
	when
		callProfile: CallProfile ( nextState == "AutoLangSelect", singleLanguage == "false", connectionType == R5RulesBean.UNKNOWN )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("SETLANG");		
		serr.setOutputVar1("g");
		serr.setNextState("Welcome-MultiLanguage");
		serr.setState(StateEngineRulesResult.DONE);
end

// Rule for setting language when historical Data (cliDataLanguage) exists
// This should logically have higher salience than the following rules without historical data
// Both rows in the SME decision matrix are combined into one rule since it doesn't matter if the
// spokenLanguage in the CustomerProfile exists or not
rule "020e_AutoLangSelect_Wireless_multiLanguageRegion_haveCliDataLanguage"
	no-loop
	salience 100
	when
		callProfile: CallProfile ( nextState == "AutoLangSelect", singleLanguage == "false", connectionType == R5RulesBean.WIRELESS )
		eval (
			 	!StringUtils.isEmpty(callProfile.getCliDataLanguage())
			 ) 
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("SETLANG");		
		serr.setOutputVar1(callProfile.getCliDataLanguage());
		serr.setNextState("Welcome-SingleLanguage");
		serr.setState(StateEngineRulesResult.DONE);
end

rule "020f_AutoLangSelect_Wireless_multiLanguageRegion_RES_haveSpokenLanguage"
	no-loop
	when
		callProfile: CallProfile ( nextState == "AutoLangSelect", singleLanguage == "false", connectionType == R5RulesBean.WIRELESS )
		customerProfile: CustomerProfile ()
		eval (
				StringUtils.equals(customerProfile.getSegment(),R5RulesBean.SEGMENT_RES) &&
				!StringUtils.isEmpty(customerProfile.getLanguageSpoken())
		)
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("SETLANG");		
		serr.setOutputVar1(customerProfile.getLanguageSpoken());
		serr.setNextState("Welcome-SingleLanguage");
		serr.setState(StateEngineRulesResult.DONE);
end

rule "020g_AutoLangSelect_Wireless_multiLanguageRegion_SME_CBU_haveSpokenLanguage"
	no-loop
	when
		callProfile: CallProfile ( nextState == "AutoLangSelect", singleLanguage == "false", connectionType == R5RulesBean.WIRELESS )
		customerProfile: CustomerProfile ()
	  	eval ( 
	  		   ( StringUtils.equals(customerProfile.getSegment(),R5RulesBean.SEGMENT_SME) || StringUtils.equals(customerProfile.getSegment(),R5RulesBean.SEGMENT_CBU)) &&
	  		   (!StringUtils.isEmpty(customerProfile.getLanguageSpoken()))
	  		 )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("SETLANG");		
		serr.setOutputVar1(customerProfile.getLanguageSpoken());
		serr.setNextState("Welcome-MultiLanguage");
		serr.setState(StateEngineRulesResult.DONE);
end

rule "020h_AutoLangSelect_Wireless_multiLanguageRegion_noSpokenLanguage"
	no-loop
	salience -1
	when
		callProfile: CallProfile ( nextState == "AutoLangSelect", singleLanguage == "false", connectionType == R5RulesBean.WIRELESS )
		CustomerProfile ( languageSpoken == "" ) ||
		CustomerProfile ( languageSpoken == null )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("SETLANG");		
		serr.setOutputVar1("g");
		serr.setNextState("Welcome-MultiLanguage");
		serr.setState(StateEngineRulesResult.DONE);
end

/*
	The following states for Welcome remain here with PROCEED action so that it's easier to add them later if required 
*/

/* SingleLanguage Welcome, skips Language selection */
rule "030a_Welcome_SingleLanguage_PlayWelcomeTrue"
	no-loop
	when
		callProfile: CallProfile ( nextState == "Welcome-SingleLanguage", playwelc != "false" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("PROCEED");
		serr.setNextState("GetINAS");
		serr.setState(StateEngineRulesResult.DONE);
end

rule "030b_Welcome_SingleLanguage_PlayWelcomeFalse"
	no-loop
	when
		callProfile: CallProfile ( nextState == "Welcome-SingleLanguage", playwelc == "false" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("PROCEED");
		serr.setNextState("GetINAS");
		serr.setState(StateEngineRulesResult.DONE);
end

/* MultiLanguage Welcome, offers Language Selection next */
rule "030c_Welcome_MultiLanguage_PlayWelcomeTrue"
	no-loop
	when
		CallProfile ( nextState == "Welcome-MultiLanguage", playwelc != "false" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("PROCEED");
		serr.setNextState("LanguageSelection");
		serr.setState(StateEngineRulesResult.DONE);
end

rule "030d_Welcome_MultiLanguage_PlayWelcomeFalse"
	no-loop
	when
		CallProfile ( nextState == "Welcome-MultiLanguage", playwelc == "false" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("PROCEED");
		serr.setNextState("LanguageSelection");
		serr.setState(StateEngineRulesResult.DONE);
end

/* Language Selection */
rule "040_LanguageSelection"
	no-loop
	when
		CallProfile ( nextState == "LanguageSelection" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("LANGSELECT");
		serr.setOutputVar1("false");
		serr.setNextState("GetINAS");
		serr.setState(StateEngineRulesResult.DONE);
end

rule "050_GetINAS"
	no-loop
		when
		CallProfile ( nextState == "GetINAS" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("SETINASACTIONS");
		serr.setOutputVar1("SME");
		serr.setNextState("PlayINAS"); 
		serr.setState(StateEngineRulesResult.DONE);
end

rule "060_PlayINAS_MAIN"
	no-loop
	when
		CallProfile ( nextState == "PlayINAS" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("EXECINASACTIONS");
		serr.setOutputVar1("MAIN");
		serr.setNextState("PhoneNumberInput");
		serr.setState(StateEngineRulesResult.DONE);
end

/* Phone Number Input*/
rule "070_PhoneNumberInput"
	no-loop
	when
		CallProfile ( nextState == "PhoneNumberInput" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("ENTERPN");
		serr.setOutputVar1("enterPhoneNumber");
		serr.setNextState("GetResultCustInfo");
		serr.setState(StateEngineRulesResult.DONE);
end

/* Get Result Cust Info before Transfer to have complete information */
rule "080_GetResultCustInfo"
	no-loop
	when
		CallProfile ( nextState == "GetResultCustInfo" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("GETRESULTCUSTINFO");
		serr.setNextState("CheckSegment");
		serr.setState(StateEngineRulesResult.DONE);
end

rule "085a_CheckSegment_RES"
	no-loop
	salience 1000
	when
		CallProfile ( nextState == "CheckSegment" )
		CustomerProfile ( segment == R5RulesBean.SEGMENT_RES)
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("PROCEED");
		serr.setNextState("Transfer");
		serr.setState(StateEngineRulesResult.DONE);
end

rule "085b_CheckSegment_CBU"
	no-loop
	salience 1000
	when
		CallProfile ( nextState == "CheckSegment" )
		CustomerProfile ( segment == R5RulesBean.SEGMENT_CBU)
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("PROCEED");
		serr.setNextState("Transfer");
		serr.setState(StateEngineRulesResult.DONE);
end

rule "085c_CheckSegment_allOthers"
	no-loop
	when
		CallProfile ( nextState == "CheckSegment" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("PROCEED");
		serr.setNextState("OpeningHoursCheck");
		serr.setState(StateEngineRulesResult.DONE);
end

// Opening Hours check to have result in callDetail for check by transfer rules
rule "090_OpeningHoursCheck"
	no-loop
	when
		CallProfile ( nextState == "OpeningHoursCheck" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("CHECKOH");
		serr.setOutputVar1("OH_SME_KMU_SHOPHOTLINE");
		serr.setNextState("CBR");
		serr.setState(StateEngineRulesResult.DONE);
end

// Use result from previous CHECKOH to offer CBR only during the day when result was != 1
// After CBR no need to check result since transfer will always be next action
rule "100a_CBR_Day"
	no-loop
	when
		CallProfile ( nextState == "CBR", resultOH != "1" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("CBR");
		serr.setNextState("Transfer");
		serr.setState(StateEngineRulesResult.DONE);
end

// During the night when oh_sme_global was 1 skip CBR
rule "100b_CBR_Night"
	no-loop
	when
		CallProfile ( nextState == "CBR", resultOH == "1" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("PROCEED");
		serr.setNextState("Transfer");
		serr.setState(StateEngineRulesResult.DONE);
end

rule "110_Transfer"
	no-loop
	when
		CallProfile ( nextState == "Transfer" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("TRANSFER");
		serr.setOutputVar1("sme/vp5smeTransfer");
		serr.setNextState("Disconnect");
		serr.setState(StateEngineRulesResult.DONE);
end

rule "200_Disconnect"
	no-loop
	when
		CallProfile ( nextState == "Disconnect" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("DISCONNECT");
		serr.setState(StateEngineRulesResult.DONE);
end

rule "201_GoodbyeDisconnect"
	no-loop
	when
		CallProfile ( nextState == "GoodbyeDisconnect" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("GOODBYE");
		serr.setState(StateEngineRulesResult.DONE);
end

/* State for Exceptions caught by StateEngine Event Handlers */
rule "900_InputError"
	no-loop
	salience -500
	when
		CallProfile ( nextState == "InputError" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("PROCEED");
		serr.setNextState("Transfer");
		serr.setState(StateEngineRulesResult.DONE);
end

rule "901_ConnectorError"
	no-loop
	salience -500
	when
		CallProfile ( nextState == "ConnectorError" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("PROCEED");
		serr.setNextState("Transfer");
		serr.setState(StateEngineRulesResult.DONE);
end

rule "902_TechError"
	no-loop
	salience -500
	when
		CallProfile ( nextState == "TechError" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("PROCEED");
		serr.setNextState("Transfer");
		serr.setState(StateEngineRulesResult.DONE);
end

/* Catch-All States */

rule "998_FALLBACK_TRANSFER"
	no-loop
	salience -10000
	when
		CallProfile ( nextState != "Disconnect" )
		serr : StateEngineRulesResult(state == StateEngineRulesResult.NOT_SET )
	then
		serr.setAction("PROCEED");
		serr.setNextState("Transfer");
		serr.setState(StateEngineRulesResult.DONE);
end
