/*
 * (c)2008 Nortel Networks Limited. All Rights Reserved.
 *
 * @(#) $Id: vp5cbu-0800724008-menu-level2.drl 5 2013-08-05 10:00:45Z tolvoph1 $
 * $Author: tolvoph1 $
 * $Date: 2013-08-05 12:00:45 +0200 (Mon, 05 Aug 2013) $
 * $Revision: 5 $
 */
package com.nortel.ema.swisscom.bal.rules.cbu.menu

import com.nortel.ema.swisscom.bal.vo.model.CustomerProfile;
import com.nortel.ema.swisscom.bal.vo.model.CustomerProducts;
import com.nortel.ema.swisscom.bal.vo.model.CallProfile;
import com.nortel.ema.swisscom.bal.rules.model.facts.R5RulesBean;
import com.nortel.ema.swisscom.bal.menu.model.ExtendedMenuOption;
import java.util.List;

global List menuOptions;
global String language;

function ExtendedMenuOption voice() {
  	  ExtendedMenuOption option = new ExtendedMenuOption();
  	  option.setName("VOICE");
  	  option.setPrompt("pm-voice");
  	  option.setSkill("VOICE");
  	  option.setEmergencyText("SA-VOICE");
  	  option.setAction("TRANSFER");
  	  return option;
}

function ExtendedMenuOption data() {
  	  ExtendedMenuOption option = new ExtendedMenuOption();
  	  option.setName("DATA");
  	  option.setPrompt("pm-data");
  	  option.setSkill("DATA");
  	  option.setEmergencyText("SA-DATA");
  	  option.setAction("TRANSFER");
  	  return option;
}

function ExtendedMenuOption blackberry() {
  	  ExtendedMenuOption option = new ExtendedMenuOption();
  	  option.setName("BB");
  	  option.setPrompt("pm-bb");
  	  option.setSkill("BB");
  	  option.setEmergencyText("SA-BLACKBERRY"); //??
  	  option.setAction("TRANSFER");
  	  return option;
}
 

rule "0800724008_Level2"
	no-loop
	when

	then
		menuOptions.add(voice());
		menuOptions.add(data());
		menuOptions.add(blackberry());
end
