/*
 * (c)2008 Nortel Networks Limited. All Rights Reserved.
 *
 * @(#) $Id: vp5cbu-0800724003-menu-level1.drl 5 2013-08-05 10:00:45Z tolvoph1 $
 * $Author: tolvoph1 $
 * $Date: 2013-08-05 12:00:45 +0200 (Mon, 05 Aug 2013) $
 * $Revision: 5 $
 */
package com.nortel.ema.swisscom.bal.rules.cbu.menu

import com.nortel.ema.swisscom.bal.vo.model.CustomerProfile;
import com.nortel.ema.swisscom.bal.vo.model.CustomerProducts;
import com.nortel.ema.swisscom.bal.vo.model.CallProfile;
import com.nortel.ema.swisscom.bal.rules.model.facts.R5RulesBean;
import com.nortel.ema.swisscom.bal.menu.model.ExtendedMenuOption;
import java.util.List;

global List menuOptions;
global String language;

function ExtendedMenuOption saOUS() {
  	  ExtendedMenuOption option = new ExtendedMenuOption();
  	  option.setName("SA_OUS");
  	  option.setPrompt("alm-serviceassurance");
  	  option.setSkill("SA_OUS");
  	  option.setEmergencyText("SA"); //??
  	  option.setAction("MENU");
  	  return option;
}

function ExtendedMenuOption order() {
  	  ExtendedMenuOption option = new ExtendedMenuOption();
  	  option.setName("ORDER");
  	  option.setPrompt("alm-order-nv");
  	  option.setSkill("ORDER");
  	  option.setEmergencyText("ORDER"); //??
  	  option.setAction("MENU");
  	  return option;
}

 
/*
   Static menu 1st level
      
   Mapping numeric menu options to actual options:
   // Novartis 1st level menu
	public static final Long MENU_SA_OUS_NV = new Long(4130);
	public static final Long MENU_ORDER_NV = new Long(4140);
	public static final Long MENU_OTHER_NV = new Long(4150);
	// Novartis 2nd menu level and VIP menu
	public static final Long MENU_ORDER_FX_NV = new Long(4540);
	public static final Long MENU_VIP_FX_NV = new Long(4541);
	public static final Long MENU_SA_FX_PW_NV = new Long(4545);
	public static final Long MENU_SA_MO_NV = new Long(4550);
	public static final Long MENU_ORDER_MO_NV = new Long(4551);
	public static final Long MENU_VIP_MO_NV = new Long(4552);
	public static final Long MENU_PAGING_NV = new Long(4560);   	=> Others
*/


rule "0800724003_Level1"
	no-loop
	when

	then
		menuOptions.add(saOUS()); //4130
		menuOptions.add(order()); //4140
end
