/*
 * (c)2008 Nortel Networks Limited. All Rights Reserved.
 *
 * @(#) $Id: vp5cbu-0800724724-menu-level1.drl 5 2013-08-05 10:00:45Z tolvoph1 $
 * $Author: tolvoph1 $
 * $Date: 2013-08-05 12:00:45 +0200 (Mon, 05 Aug 2013) $
 * $Revision: 5 $
 */
package com.nortel.ema.swisscom.bal.rules.cbu.menu

import com.nortel.ema.swisscom.bal.menu.model.ExtendedMenuOption;
import com.nortel.ema.swisscom.bal.rules.model.facts.R5RulesBean;
import com.nortel.ema.swisscom.bal.vo.model.CustomerProfile;
import com.nortel.ema.swisscom.bal.vo.model.CustomerProducts;
import com.nortel.ema.swisscom.bal.vo.model.CallProfile;

import java.util.List;

global List menuOptions;
global String language;

function ExtendedMenuOption menuSA() {
  	  ExtendedMenuOption option = new ExtendedMenuOption();
  	  option.setName("SA");
  	  option.setPrompt("alm-serviceassurance");
  	  option.setSkill("SA");
  	  option.setAction("MENU");
  	  option.setEmergencyText("SA");
  	  return option;
}

function ExtendedMenuOption menuSF() {
  	  ExtendedMenuOption option = new ExtendedMenuOption();
  	  option.setName("SF");
  	  option.setPrompt("alm-servicefulfilment");
  	  option.setSkill("SF");
  	  option.setAction("MENU");
  	  option.setEmergencyText("SF");
  	  return option;
}

function ExtendedMenuOption hiddenTransfer() {
  	  ExtendedMenuOption option = new ExtendedMenuOption();
  	  option.setName("CUC_International");
  	  option.setPosition(9);
  	  option.setAction("TRANSFER");
  	  return option;
}

rule "080072472424_Level1"
	no-loop
	when

	then
		menuOptions.add(menuSA());
		menuOptions.add(menuSF());
		menuOptions.add(hiddenTransfer());
end
